name: Build and upload JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Copy JAR to repo root
        run: |
          # copia qualquer JAR produzido para a raiz do workspace (repo)
          cp target/*.jar . || true
          ls -la

      - name: Commit and push JAR to repo root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # configura usuário para o commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # adiciona JAR(s) na raiz se existirem
          git add *.jar || echo "No jar to add"
          # só commita se houver mudanças staged
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add built JAR from CI [skip ci]"
            git push
          fi

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: todoapp-jar
          path: target/*.jar
